# Generated by Django 4.2.7 on 2023-11-18 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientTodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='noted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 11, 18, 20, 15, 47, 692807)),
        ),
    ]
