# Generated by Django 4.2.7 on 2023-11-18 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientTodo', '0002_task_noted_alter_card_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='data',
        ),
        migrations.AddField(
            model_name='card',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 18, 20, 23, 24, 302183)),
        ),
    ]
