# Generated by Django 4.2.7 on 2023-11-18 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientTodo', '0003_remove_card_data_card_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 18, 21, 2, 24, 568553)),
        ),
    ]
